basic.showString("X")
basic.forever(function () {
    led.plot(0, 0)
    SuperBit.Servo(SuperBit.enServo.S8, 0)
    basic.pause(1000)
    led.plot(1, 0)
    SuperBit.Servo(SuperBit.enServo.S8, 90)
    basic.pause(1000)
    led.plot(2, 0)
    SuperBit.Servo(SuperBit.enServo.S8, 180)
    basic.pause(1000)
    led.plot(3, 0)
    SuperBit.Servo(SuperBit.enServo.S8, 90)
    basic.pause(1000)
})
